name: FactionsSpectator
main: tollenaar.stephen.FactionsSpectator.Core
version: 6.0
authors: [guitargun]
loadafter: [FactionsUUID]
description: able to get into spectator mode while inside your claims
api-version: 1.16